services:
  test-db:
    image: postgres
    restart: always
    container_name: js-van-blog
    ports:
      - '4444:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test